export * from './career-study-plan.schema';
export * from './career-teacher-course.schema';
export * from './dashboards.schema';
export * from './keys.schema';
export * from './securities.schema';
export * from './students.schema';
export * from './universities.schema';
export * from './university-course.schema';
export * from './university-teacher.schema';
